id: A76B32662
title: Prayer to the Omniscient Longchen Rabjam
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:06:26.136419
  last_modified_at: 2022-03-01 01:06:26.136422
