id: A76B32662
title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from Afar'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:06:26.134633
  last_modified_at: 2022-03-01 01:06:26.134642
